---
- name: List IAM Users
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all IAM users
      amazon.aws.iam_user_info:
      register: iam_users

    - name: Display IAM users
      debug:
        msg: "{{ item.user_name }}"
      loop: "{{ iam_users.iam_users }}"
      loop_control:
        label: "{{ item.user_name }}"